name       : python-terminado
version    : 0.12.1
release    : 6
source     :
    - https://pypi.python.org/packages/source/t/terminado/terminado-0.12.1.tar.gz : b20fd93cc57c1678c799799d117874367cc07a3d2d55be95205b1a88fa08393f
homepage   : https://github.com/jupyter/terminado
license    : BSD-2-Clause
component  : programming.python
summary    : A python websocket server backend for xterm.js
description: |
    This is a Tornado websocket backend for the Xterm.js Javascript terminal emulator library.
builddeps  :
    - ptyprocess
    - python-nose
    - python-pytest
    - python-tornado
rundeps    :
    - ptyprocess
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # workaround new readline defaults
    echo "set enable-bracketed-paste off" > .inputrc
    export INPUTRC=$PWD/.inputrc
    %python3_test nosetests-%python3_version%
