name       : python-terminado
version    : 0.13.1
release    : 7
source     :
    - https://github.com/jupyter/terminado/releases/download/v0.13.1/terminado-0.13.1.tar.gz : 5b82b5c6e991f0705a76f961f43262a7fb1e55b093c16dca83f16384a7f39b7b
homepage   : https://github.com/jupyter/terminado
license    : BSD-2-Clause
component  : programming.python
summary    : A python websocket server backend for xterm.js
description: |
    This is a Tornado websocket backend for the Xterm.js Javascript terminal emulator library.
builddeps  :
    - ptyprocess
    - python-nose
    - python-pytest
    - python-tornado
rundeps    :
    - ptyprocess
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # workaround new readline defaults
    echo "set enable-bracketed-paste off" > .inputrc
    export INPUTRC=$PWD/.inputrc
    %python3_test nosetests-%python3_version%
