name       : python-terminado
version    : 0.8.2
release    : 2
source     :
    - https://pypi.python.org/packages/source/t/terminado/terminado-0.8.2.tar.gz : de08e141f83c3a0798b050ecb097ab6259c3f0331b2f7b7750c9075ced2c20c2
license    : BSD-2-Clause
component  : programming.python
summary    : A python websocket server backend for xterm.js
description: |
    This is a Tornado websocket backend for the Xterm.js Javascript terminal emulator library.
builddeps  :
    - ptyprocess
    - python-nose
    - python-tornado
rundeps    :
    - ptyprocess
    - python-tornado
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests-%python3_version%
