name       : python-terminado
version    : 0.8.1
release    : 1
source     :
    - https://pypi.python.org/packages/67/84/ce0ebd0f60e1cbe040f8e065eef7063855d59d9cf5e6438b3f8439fc7e15/terminado-0.8.1.tar.gz : 55abf9ade563b8f9be1f34e4233c7b7bde726059947a593322e8a553cc4c067a
license    : BSD-2-Clause
component  : programming.python
summary    : A python websocket server backend for xterm.js
description: |
    This is a Tornado websocket backend for the Xterm.js Javascript terminal
    emulator library.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - ptyprocess
    - python-tornado
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

